
server.port=8080
spring.application.name=backend
exchange.api.url=${EXCHANGE_API_URL}
exchange.api.key=${EXCHANGE_API_KEY}


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=